[project]
name = "attach-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.2.1.dev345",
    "fastapi[standard]>=0.115.8",
]

[dependency-groups]
dev = [
    "ruff>=0.9.6",
]
